import "./globals.css";
import { Inter, Lora, Playfair_Display } from "next/font/google";
import { ReactNode } from "react";
import { Metadata } from "next";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter", 
});
export const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});
export const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});
export const metadata:Metadata = {
  title: "Next News Site",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }:RootLayoutProps) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <header>
          <Navbar />
        </header>
        <main className="my-15 mx-10 py-4 px-8">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
